### ISSUE TITLE
Review & Confirmation Checklist #1

### ISSUE THREAD

**Issue by domini4** [Educating-Autistic-Software-Engineers/Collaboration-Station#1]
1. Video Functionality

- [ ]  Ensure the background in videos is blurry.
- [x]  Enable the ability to turn videos and messaged on and off. Screen space will be taken up by scratch GUI
- [x]  Allow users to mute just their video (i.e., they aren't seeing themselves on the screen).
- [x]  Ensure there is an audio option (allow for audio to be on and not video or the reverse).
- [x] videos should be right corner right side
- [x] Videos should appear in a 2 column grid.

2. Chat Features

- [x]  Enable chat functionality for users.
- [x]  Allow users to hide the chat.
- [x] Chat window should disappear when users hide chat.
- [x]  Chat should be white background with black text for accessibility. 

3. User Management

- [x]  Allow instructors or leaders to kick out participants.
- [x]  Enable instructors to interact with students within the project environment.
- [x]  Ensure instructors have the same capabilities as students in the project.
- [x]  Allow admin to add or remove projects to users.

4. Project Management

- [x]  Provide an option to pick an existing project or start a new project from the login screen after signing in.
- [x]  Implement an easy-to-remember way of signing in.
- [x]  Allow users to be able to switch back and fourth between CollaborationStation coding page & projects page.
- [ ] Admin should be able to allow agora and ably access for select projects. Agora and ably not available by default.

5. Collaboration Tools

- [x]  Enable users to work and program with others collaboratively.

Additional Notes
- [ ] update README
- [x] make sure that the EdASE logo redirects to edase.org
- [x] top header (CollaborationStation is removed for space.
- [x]  Ensure all features are user-friendly and intuitive.
- [ ]  Test all functionalities thoroughly to ensure smooth operation.
- [ ]  Provide clear documentation and tutorials for users and instructors.
- [ ]  Update the repo
- [x] connect with the "real" domain

**Comment by paigerodeghero** [comment]
> 1. Video Functionality
> 
> * [ ]   Ensure the background in videos is blurry.
> * [ ]   Enable the ability to turn videos and messaged on and off. Screen space will be taken up by scratch GUI
> * [x]   Allow users to mute just their video (i.e., they aren't seeing themselves on the screen).
> * [x]   Ensure there is an audio option (allow for audio to be on and not video or the reverse).
> * [x]  videos should be right corner right side
> * [ ]  Videos should appear in a 2 column grid.
> 
> 2. Chat Features
> 
> * [x]   Enable chat functionality for users.
> * [x]   Allow users to hide the chat.
> * [x]  Chat window should disappear when users hide chat.
> * [ ]   Chat should be white background with black text for accessibility.
> 
> 3. User Management
> 
> * [x]   Allow instructors or leaders to kick out participants.
> * [x]   Enable instructors to interact with students within the project environment.
> * [x]   Ensure instructors have the same capabilities as students in the project.
> * [x]   Allow admin to add or remove projects to users.
> 
> 4. Project Management
> 
> * [x]   Provide an option to pick an existing project or start a new project from the login screen after signing in.
> * [x]   Implement an easy-to-remember way of signing in.
> * [x]   Allow users to be able to switch back and fourth between CollaborationStation coding page & projects page.
> * [ ]  Admin should be able to allow agora and ably access for select projects. Agora and ably not available by default.
> 
> 5. Collaboration Tools
> 
> * [x]   Enable users to work and program with others collaboratively.
> * [ ]   Allow users to use the drawing features in Scratch collaboratively with others.
> 
> Additional Notes
> 
> * [ ]  update README
> * [x]  make sure that the EdASE logo redirects to edase.org
> * [x]  top header (CollaborationStation is removed for space.
> * [ ]   Ensure all features are user-friendly and intuitive.
> * [ ]   Test all functionalities thoroughly to ensure smooth operation.
> * [ ]   Provide clear documentation and tutorials for users and instructors.
> * [ ]   Update the repo
> * [x]  connect with the "real" domain

**Comment by paigerodeghero** [comment]
let's ignore the additional note about centering. I removed it in the comment above
