### ISSUE TITLE
 Review & Confirmation Checklist

### ISSUE THREAD

**Issue by Quantiset** [Educating-Autistic-Software-Engineers/Collaboration-Station#2]
1. Video Functionality
   - [ ] Ensure the background in videos is blurry.
   - [ ] Enable the ability to turn videos on and off.
   - [ ] Allow users to hide just their video (i.e., they aren't seeing themselves on the screen).
   - [ ] Ensure there is an audio option (allow for audio to be on and not video or the reverse).

2. Chat Features
   - [ ] Enable chat functionality for users.
   - [ ] Allow users to hide the chat.

3. User Management
   - [ ] Allow instructors or leaders to kick out participants.
   - [ ] Enable instructors to interact with students within the project environment.
   - [ ] Ensure instructors have the same capabilities as students in the project.

4. Project Management
   - [ ] Provide an option to pick an existing project or start a new project from the login screen after signing in.
   - [ ] Implement an easy-to-remember way of signing in.
   - [ ] Allow users to be able to switch back and fourth between CollaborationStation coding page & projects page.

5. Collaboration Tools
   - [ ] Enable users to work and program with others collaboratively.
   - [ ] Allow users to use the drawing features in Scratch collaboratively with others.

Additional Notes
   - [ ] Ensure all features are user-friendly and intuitive.
   - [ ] Test all functionalities thoroughly to ensure smooth operation.
   - [ ] Provide clear documentation and tutorials for users and instructors.
   - [ ] Update the repo

**Comment by Quantiset** [comment]
Duplicate of #1
